-- ==========================================================
-- SCRIPT DE INSTALACIÓN FINAL - PROYECTO 2 (UMG)
-- OBJETIVO: INTEGRAR TABLAS, PL/SQL Y DATOS HISTÓRICOS
-- ==========================================================

-- 1. LIMPIEZA DE ESTRUCTURAS (Para evitar errores de "Ya existe")
DROP TABLE DETALLE_FACTURA CASCADE CONSTRAINTS;
DROP TABLE FACTURA CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TIPO_CLIENTE CASCADE CONSTRAINTS;

-- 2. CREACIÓN DE TABLAS
CREATE TABLE TIPO_CLIENTE (
    ID_TIPO NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(100)
);

CREATE TABLE CLIENTE (
    NIT VARCHAR2(20) PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(150),
    ID_TIPO NUMBER,
    CONSTRAINT FK_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE(ID_TIPO)
);

CREATE TABLE MARCA (
    ID_MARCA NUMBER PRIMARY KEY,
    NOMBRE_MARCA VARCHAR2(100)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR2(150),
    PRECIO NUMBER(10,2),
    ID_MARCA NUMBER,
    CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER PRIMARY KEY,
    FECHA DATE,
    NIT_CLIENTE VARCHAR2(20),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (NIT_CLIENTE) REFERENCES CLIENTE(NIT)
);

CREATE TABLE DETALLE_FACTURA (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    SUBTOTAL NUMBER(10,2),
    CONSTRAINT FK_FACT_DET FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
    CONSTRAINT FK_PROD_DET FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- 3. PROCEDIMIENTO PL/SQL PARA CARGA DE CATÁLOGOS
CREATE OR REPLACE PROCEDURE SP_CARGAR_CATALOGOS(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR 
    SELECT p.id_producto, p.nombre_producto, p.precio, m.nombre_marca
    FROM PRODUCTO p
    JOIN MARCA m ON p.id_marca = m.id_marca;
END;
/

-- 4. INSERCIÓN DE CATÁLOGOS INICIALES
INSERT INTO TIPO_CLIENTE VALUES (1, 'CLIENTE FRECUENTE');

INSERT INTO MARCA VALUES (1, 'Logitech');
INSERT INTO MARCA VALUES (2, 'Razer');
INSERT INTO MARCA VALUES (3, 'ASUS');
INSERT INTO MARCA VALUES (4, 'HyperX');
INSERT INTO MARCA VALUES (5, 'Sony');

-- 5. CATÁLOGO DE PRODUCTOS (Para Reporte Hash O(1))
INSERT INTO PRODUCTO VALUES (101, 'Mouse G502 Hero', 450.00, 1);
INSERT INTO PRODUCTO VALUES (102, 'Teclado BlackWidow V4', 1200.00, 2);
INSERT INTO PRODUCTO VALUES (103, 'Mouse DeathAdder V3', 600.00, 2);
INSERT INTO PRODUCTO VALUES (201, 'Monitor TUF Gaming 27"', 2800.00, 3);
INSERT INTO PRODUCTO VALUES (202, 'Tarjeta Video RTX 4060', 3500.00, 3);
INSERT INTO PRODUCTO VALUES (301, 'Audífonos Cloud II', 850.00, 4);
INSERT INTO PRODUCTO VALUES (302, 'Micrófono QuadCast', 1100.00, 4);
INSERT INTO PRODUCTO VALUES (401, 'Audífonos WH-1000XM5', 2900.00, 5);

-- 6. DATOS HISTÓRICOS PARA EL GRAFO
-- Cliente principal para las pruebas de trazabilidad
INSERT INTO CLIENTE VALUES ('14020319', 'Estudiante UMG Chimaltenango', 1);

-- Facturas de los años requeridos (2024, 2025, 2026)
INSERT INTO FACTURA VALUES (7001, TO_DATE('15/05/2024', 'DD/MM/YYYY'), '14020319');
INSERT INTO FACTURA VALUES (8001, TO_DATE('20/11/2025', 'DD/MM/YYYY'), '14020319');
INSERT INTO FACTURA VALUES (9001, TO_DATE('10/01/2026', 'DD/MM/YYYY'), '14020319');

COMMIT;